name: Publish Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Update docs when changes are pushed to the main branch

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Generate Documentation
        run: npm run doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs